import { MigrationInterface, QueryRunner } from "typeorm";

export class Auto1785355043599 implements MigrationInterface {
    name = 'Auto1785355043599'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_sessions" DROP CONSTRAINT "user_sessions_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "academic_periods" DROP CONSTRAINT "academic_periods_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP CONSTRAINT "subjects_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "enrollments_student_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "enrollments_course_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "group_memberships" DROP CONSTRAINT "group_memberships_assigned_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "group_memberships" DROP CONSTRAINT "group_memberships_enrollment_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "group_memberships" DROP CONSTRAINT "group_memberships_class_group_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "class_groups" DROP CONSTRAINT "class_groups_course_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "class_sessions" DROP CONSTRAINT "class_sessions_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "class_sessions" DROP CONSTRAINT "class_sessions_class_group_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "class_sessions" DROP CONSTRAINT "class_sessions_course_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "class_sessions" DROP CONSTRAINT "class_sessions_lesson_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "lessons_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "lessons_course_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "courses_teacher_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "courses_academic_period_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "courses_subject_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "sync_operations" DROP CONSTRAINT "sync_operations_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "activities_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "activities_lesson_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "activities_course_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "attachments_uploaded_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "attachments_exception_request_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "exception_requests_resolved_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "exception_requests_requested_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "exception_requests_activity_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "exception_requests_class_session_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "exception_requests_enrollment_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "exception_requests_course_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "signature_records_canceled_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "signature_records_exception_request_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "signature_records_registered_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "signature_records_class_group_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "signature_records_class_session_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "signature_records_enrollment_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "signature_records_activity_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" DROP CONSTRAINT "qr_credentials_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" DROP CONSTRAINT "qr_credentials_enrollment_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "attendance_records_exception_request_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "attendance_records_registered_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "attendance_records_enrollment_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "attendance_records_class_session_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."user_sessions_user_active_idx"`);
        await queryRunner.query(`DROP INDEX "public"."students_name_idx"`);
        await queryRunner.query(`DROP INDEX "public"."enrollments_course_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."group_memberships_active_uk"`);
        await queryRunner.query(`DROP INDEX "public"."group_memberships_group_active_idx"`);
        await queryRunner.query(`DROP INDEX "public"."class_sessions_course_date_idx"`);
        await queryRunner.query(`DROP INDEX "public"."class_sessions_group_date_idx"`);
        await queryRunner.query(`DROP INDEX "public"."lessons_course_idx"`);
        await queryRunner.query(`DROP INDEX "public"."activities_course_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."exceptions_course_status_idx"`);
        await queryRunner.query(`DROP INDEX "public"."signature_client_operation_uk"`);
        await queryRunner.query(`DROP INDEX "public"."signatures_activity_enrollment_idx"`);
        await queryRunner.query(`DROP INDEX "public"."signatures_session_idx"`);
        await queryRunner.query(`DROP INDEX "public"."qr_credentials_active_uk"`);
        await queryRunner.query(`DROP INDEX "public"."audit_entity_date_idx"`);
        await queryRunner.query(`DROP INDEX "public"."attendance_client_operation_uk"`);
        await queryRunner.query(`DROP INDEX "public"."attendance_enrollment_idx"`);
        await queryRunner.query(`ALTER TABLE "academic_periods" DROP CONSTRAINT "academic_period_dates_ck"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "enrollments_withdrawal_ck"`);
        await queryRunner.query(`ALTER TABLE "group_memberships" DROP CONSTRAINT "group_membership_dates_ck"`);
        await queryRunner.query(`ALTER TABLE "class_sessions" DROP CONSTRAINT "class_sessions_time_ck"`);
        await queryRunner.query(`ALTER TABLE "class_sessions" DROP CONSTRAINT "class_sessions_close_ck"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "lessons_sequence_ck"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "courses_tolerance_ck"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_lower_ck"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "activities_max_ck"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "activities_value_ck"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "attachments_size_ck"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "exception_resolution_ck"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "signature_quantity_ck"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "signature_cancellation_ck"`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" DROP CONSTRAINT "qr_credentials_version_ck"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "attendance_check_times_ck"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "enrollments_course_student_uk"`);
        await queryRunner.query(`ALTER TABLE "group_memberships" DROP CONSTRAINT "group_membership_version_uk"`);
        await queryRunner.query(`ALTER TABLE "class_groups" DROP CONSTRAINT "class_groups_code_uk"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "courses_offering_uk"`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" DROP CONSTRAINT "qr_credentials_version_uk"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "attendance_session_enrollment_uk"`);
        await queryRunner.query(`ALTER TABLE "enrollments" ALTER COLUMN "enrolled_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "group_memberships" ALTER COLUMN "assigned_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sync_operations" ALTER COLUMN "received_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "attachments_storage_key_uk"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ALTER COLUMN "requested_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "signature_records" ALTER COLUMN "registered_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" DROP CONSTRAINT "qr_credentials_token_hash_uk"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_pkey"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user_sessions" ADD CONSTRAINT "FK_e9658e959c490b0a634dfc54783" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "academic_periods" ADD CONSTRAINT "FK_ce7321356447fb7ff25796bf01b" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD CONSTRAINT "FK_c9006b576b282e18dba027d6a38" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_b79d0bf01779fdf9cfb6b092af3" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_307813fe255896d6ebf3e6cd55c" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_memberships" ADD CONSTRAINT "FK_201a35ba15360d2be0f49f87968" FOREIGN KEY ("class_group_id") REFERENCES "class_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_memberships" ADD CONSTRAINT "FK_eaf10f573c6658ad490ef2be10a" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_memberships" ADD CONSTRAINT "FK_205d85b0fa4d4e1e6b0a7d6f187" FOREIGN KEY ("assigned_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_groups" ADD CONSTRAINT "FK_c049df9d565461e9fab4de361af" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_sessions" ADD CONSTRAINT "FK_05aba5b1dd690db8dd7c06919e9" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_sessions" ADD CONSTRAINT "FK_1397d1e5d657291c564326ef505" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_sessions" ADD CONSTRAINT "FK_355019a6577e38674ddfa5bd264" FOREIGN KEY ("class_group_id") REFERENCES "class_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_sessions" ADD CONSTRAINT "FK_1ecd9efd9287f6532bc2bb2f354" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_3c4e299cf8ed04093935e2e22fe" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_b96adc7c3e06624edae3e0a01ae" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_05f921ecf5310e1204a95d824a9" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_35dbc76f1896b96d63bc7a23329" FOREIGN KEY ("academic_period_id") REFERENCES "academic_periods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_fad76a730ee7f68d0a59652fb12" FOREIGN KEY ("teacher_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sync_operations" ADD CONSTRAINT "FK_fc210cc9a22c0feee5e88a27ae9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_5c2d04397bd5264e1f7a7ac2deb" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_8be9a128683642f952474cbc22c" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_eadf67c38263ba30b296d40f033" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_c2372cfa0329dfd4c86cc2cc294" FOREIGN KEY ("exception_request_id") REFERENCES "exception_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_e25812e3fd9b3f3edf11b2c5d58" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "FK_31e5a9f12a347c6d5f479ee18a7" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "FK_f1d43ae3dee5680d47fd90412a2" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "FK_e255e1307395d3b65c717023b8f" FOREIGN KEY ("class_session_id") REFERENCES "class_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "FK_917be94d76ac1a0aa1f37995e89" FOREIGN KEY ("activity_id") REFERENCES "activities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "FK_1287c7c37b03b712ddd4b37a28d" FOREIGN KEY ("requested_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "FK_e7ed486410813c9cb952e095c43" FOREIGN KEY ("resolved_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "FK_8186ada3c3903b1629e83cbe919" FOREIGN KEY ("activity_id") REFERENCES "activities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "FK_e0689b96ec280bb421ac61ef16c" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "FK_df6155c0558ff1dec25dd159f3c" FOREIGN KEY ("class_session_id") REFERENCES "class_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "FK_ffd5b0acc25ed64ac8ccd0e8906" FOREIGN KEY ("class_group_id") REFERENCES "class_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "FK_e764583de484ea61eadd00bd611" FOREIGN KEY ("registered_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "FK_4540b5657a6ed221808922077fd" FOREIGN KEY ("exception_request_id") REFERENCES "exception_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "FK_5ff9bdcc5783744c7825e86df3c" FOREIGN KEY ("canceled_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" ADD CONSTRAINT "FK_805dcea713b2ca37de557ec2ac9" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" ADD CONSTRAINT "FK_ef95cecc71ad1443d04f9be1c0f" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_8c6d588fe4bc0388eb669fcc5f8" FOREIGN KEY ("class_session_id") REFERENCES "class_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_ac1298d6bec15b271f734c4e5d6" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_ab6c85ec19c440d0bbe1ede0ae5" FOREIGN KEY ("registered_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_c2a103593762e0cb91dcdf0f3d2" FOREIGN KEY ("exception_request_id") REFERENCES "exception_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_c2a103593762e0cb91dcdf0f3d2"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_ab6c85ec19c440d0bbe1ede0ae5"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_ac1298d6bec15b271f734c4e5d6"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_8c6d588fe4bc0388eb669fcc5f8"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" DROP CONSTRAINT "FK_ef95cecc71ad1443d04f9be1c0f"`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" DROP CONSTRAINT "FK_805dcea713b2ca37de557ec2ac9"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "FK_5ff9bdcc5783744c7825e86df3c"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "FK_4540b5657a6ed221808922077fd"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "FK_e764583de484ea61eadd00bd611"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "FK_ffd5b0acc25ed64ac8ccd0e8906"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "FK_df6155c0558ff1dec25dd159f3c"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "FK_e0689b96ec280bb421ac61ef16c"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "FK_8186ada3c3903b1629e83cbe919"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "FK_e7ed486410813c9cb952e095c43"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "FK_1287c7c37b03b712ddd4b37a28d"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "FK_917be94d76ac1a0aa1f37995e89"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "FK_e255e1307395d3b65c717023b8f"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "FK_f1d43ae3dee5680d47fd90412a2"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "FK_31e5a9f12a347c6d5f479ee18a7"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_e25812e3fd9b3f3edf11b2c5d58"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_c2372cfa0329dfd4c86cc2cc294"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_eadf67c38263ba30b296d40f033"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_8be9a128683642f952474cbc22c"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_5c2d04397bd5264e1f7a7ac2deb"`);
        await queryRunner.query(`ALTER TABLE "sync_operations" DROP CONSTRAINT "FK_fc210cc9a22c0feee5e88a27ae9"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_fad76a730ee7f68d0a59652fb12"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_35dbc76f1896b96d63bc7a23329"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_05f921ecf5310e1204a95d824a9"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "FK_b96adc7c3e06624edae3e0a01ae"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "FK_3c4e299cf8ed04093935e2e22fe"`);
        await queryRunner.query(`ALTER TABLE "class_sessions" DROP CONSTRAINT "FK_1ecd9efd9287f6532bc2bb2f354"`);
        await queryRunner.query(`ALTER TABLE "class_sessions" DROP CONSTRAINT "FK_355019a6577e38674ddfa5bd264"`);
        await queryRunner.query(`ALTER TABLE "class_sessions" DROP CONSTRAINT "FK_1397d1e5d657291c564326ef505"`);
        await queryRunner.query(`ALTER TABLE "class_sessions" DROP CONSTRAINT "FK_05aba5b1dd690db8dd7c06919e9"`);
        await queryRunner.query(`ALTER TABLE "class_groups" DROP CONSTRAINT "FK_c049df9d565461e9fab4de361af"`);
        await queryRunner.query(`ALTER TABLE "group_memberships" DROP CONSTRAINT "FK_205d85b0fa4d4e1e6b0a7d6f187"`);
        await queryRunner.query(`ALTER TABLE "group_memberships" DROP CONSTRAINT "FK_eaf10f573c6658ad490ef2be10a"`);
        await queryRunner.query(`ALTER TABLE "group_memberships" DROP CONSTRAINT "FK_201a35ba15360d2be0f49f87968"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_307813fe255896d6ebf3e6cd55c"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_b79d0bf01779fdf9cfb6b092af3"`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP CONSTRAINT "FK_c9006b576b282e18dba027d6a38"`);
        await queryRunner.query(`ALTER TABLE "academic_periods" DROP CONSTRAINT "FK_ce7321356447fb7ff25796bf01b"`);
        await queryRunner.query(`ALTER TABLE "user_sessions" DROP CONSTRAINT "FK_e9658e959c490b0a634dfc54783"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "PK_1bb179d048bbc581caa3b013439"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" ADD CONSTRAINT "qr_credentials_token_hash_uk" UNIQUE ("token_hash")`);
        await queryRunner.query(`ALTER TABLE "signature_records" ALTER COLUMN "registered_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ALTER COLUMN "requested_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "attachments_storage_key_uk" UNIQUE ("storage_key")`);
        await queryRunner.query(`ALTER TABLE "sync_operations" ALTER COLUMN "received_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "group_memberships" ALTER COLUMN "assigned_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "enrollments" ALTER COLUMN "enrolled_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "attendance_session_enrollment_uk" UNIQUE ("class_session_id", "enrollment_id")`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" ADD CONSTRAINT "qr_credentials_version_uk" UNIQUE ("enrollment_id", "version")`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "courses_offering_uk" UNIQUE ("subject_id", "academic_period_id", "parallel")`);
        await queryRunner.query(`ALTER TABLE "class_groups" ADD CONSTRAINT "class_groups_code_uk" UNIQUE ("course_id", "code")`);
        await queryRunner.query(`ALTER TABLE "group_memberships" ADD CONSTRAINT "group_membership_version_uk" UNIQUE ("class_group_id", "enrollment_id", "assigned_at")`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_course_student_uk" UNIQUE ("course_id", "student_id")`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "attendance_check_times_ck" CHECK (((check_out_at IS NULL) OR (check_in_at IS NULL) OR (check_out_at >= check_in_at)))`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" ADD CONSTRAINT "qr_credentials_version_ck" CHECK ((version > 0))`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "signature_cancellation_ck" CHECK ((((canceled_at IS NULL) AND (canceled_by IS NULL) AND (cancellation_reason IS NULL)) OR ((canceled_at IS NOT NULL) AND (canceled_by IS NOT NULL) AND (cancellation_reason IS NOT NULL))))`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "signature_quantity_ck" CHECK ((quantity <> 0))`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "exception_resolution_ck" CHECK ((((status = ANY (ARRAY['APPROVED'::exception_status, 'REJECTED'::exception_status])) AND (resolved_by IS NOT NULL) AND (resolved_at IS NOT NULL)) OR (status <> ALL (ARRAY['APPROVED'::exception_status, 'REJECTED'::exception_status]))))`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "attachments_size_ck" CHECK ((size_bytes > 0))`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "activities_value_ck" CHECK ((signature_value >= (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "activities_max_ck" CHECK ((max_signatures > 0))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_lower_ck" CHECK (((email)::text = lower((email)::text)))`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "courses_tolerance_ck" CHECK (((late_tolerance_minutes >= 0) AND (late_tolerance_minutes <= 180)))`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "lessons_sequence_ck" CHECK (((sequence_number IS NULL) OR (sequence_number > 0)))`);
        await queryRunner.query(`ALTER TABLE "class_sessions" ADD CONSTRAINT "class_sessions_close_ck" CHECK (((closed_at IS NULL) OR (opened_at IS NOT NULL)))`);
        await queryRunner.query(`ALTER TABLE "class_sessions" ADD CONSTRAINT "class_sessions_time_ck" CHECK (((ends_at IS NULL) OR (ends_at > starts_at)))`);
        await queryRunner.query(`ALTER TABLE "group_memberships" ADD CONSTRAINT "group_membership_dates_ck" CHECK (((removed_at IS NULL) OR (removed_at >= assigned_at)))`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_withdrawal_ck" CHECK ((((status = 'WITHDRAWN'::enrollment_status) AND (withdrawn_at IS NOT NULL)) OR (status <> 'WITHDRAWN'::enrollment_status)))`);
        await queryRunner.query(`ALTER TABLE "academic_periods" ADD CONSTRAINT "academic_period_dates_ck" CHECK ((end_date >= start_date))`);
        await queryRunner.query(`CREATE INDEX "attendance_enrollment_idx" ON "attendance_records" ("enrollment_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "attendance_client_operation_uk" ON "attendance_records" ("client_operation_id") WHERE (client_operation_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "audit_entity_date_idx" ON "audit_logs" ("entity_type", "entity_id", "created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "qr_credentials_active_uk" ON "qr_credentials" ("enrollment_id") WHERE (revoked_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "signatures_session_idx" ON "signature_records" ("class_session_id") `);
        await queryRunner.query(`CREATE INDEX "signatures_activity_enrollment_idx" ON "signature_records" ("activity_id", "enrollment_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "signature_client_operation_uk" ON "signature_records" ("client_operation_id") WHERE (client_operation_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "exceptions_course_status_idx" ON "exception_requests" ("course_id", "status") `);
        await queryRunner.query(`CREATE INDEX "activities_course_status_idx" ON "activities" ("course_id", "status") `);
        await queryRunner.query(`CREATE INDEX "lessons_course_idx" ON "lessons" ("course_id") `);
        await queryRunner.query(`CREATE INDEX "class_sessions_group_date_idx" ON "class_sessions" ("class_group_id", "session_date") `);
        await queryRunner.query(`CREATE INDEX "class_sessions_course_date_idx" ON "class_sessions" ("course_id", "session_date") `);
        await queryRunner.query(`CREATE INDEX "group_memberships_group_active_idx" ON "group_memberships" ("class_group_id", "removed_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "group_memberships_active_uk" ON "group_memberships" ("class_group_id", "enrollment_id") WHERE (removed_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "enrollments_course_status_idx" ON "enrollments" ("course_id", "status") `);
        await queryRunner.query(`CREATE INDEX "students_name_idx" ON "students" ("first_name", "last_name") `);
        await queryRunner.query(`CREATE INDEX "user_sessions_user_active_idx" ON "user_sessions" ("user_id", "created_at") WHERE (revoked_at IS NULL)`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "attendance_records_class_session_id_fkey" FOREIGN KEY ("class_session_id") REFERENCES "class_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "attendance_records_enrollment_id_fkey" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "attendance_records_registered_by_fkey" FOREIGN KEY ("registered_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "attendance_records_exception_request_id_fkey" FOREIGN KEY ("exception_request_id") REFERENCES "exception_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" ADD CONSTRAINT "qr_credentials_enrollment_id_fkey" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" ADD CONSTRAINT "qr_credentials_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "signature_records_activity_id_fkey" FOREIGN KEY ("activity_id") REFERENCES "activities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "signature_records_enrollment_id_fkey" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "signature_records_class_session_id_fkey" FOREIGN KEY ("class_session_id") REFERENCES "class_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "signature_records_class_group_id_fkey" FOREIGN KEY ("class_group_id") REFERENCES "class_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "signature_records_registered_by_fkey" FOREIGN KEY ("registered_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "signature_records_exception_request_id_fkey" FOREIGN KEY ("exception_request_id") REFERENCES "exception_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "signature_records_canceled_by_fkey" FOREIGN KEY ("canceled_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "exception_requests_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "exception_requests_enrollment_id_fkey" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "exception_requests_class_session_id_fkey" FOREIGN KEY ("class_session_id") REFERENCES "class_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "exception_requests_activity_id_fkey" FOREIGN KEY ("activity_id") REFERENCES "activities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "exception_requests_requested_by_fkey" FOREIGN KEY ("requested_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "exception_requests_resolved_by_fkey" FOREIGN KEY ("resolved_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "attachments_exception_request_id_fkey" FOREIGN KEY ("exception_request_id") REFERENCES "exception_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "attachments_uploaded_by_fkey" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "activities_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "activities_lesson_id_fkey" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "activities_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sync_operations" ADD CONSTRAINT "sync_operations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "courses_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "courses_academic_period_id_fkey" FOREIGN KEY ("academic_period_id") REFERENCES "academic_periods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "courses_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "lessons_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "lessons_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_sessions" ADD CONSTRAINT "class_sessions_lesson_id_fkey" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_sessions" ADD CONSTRAINT "class_sessions_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_sessions" ADD CONSTRAINT "class_sessions_class_group_id_fkey" FOREIGN KEY ("class_group_id") REFERENCES "class_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_sessions" ADD CONSTRAINT "class_sessions_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_groups" ADD CONSTRAINT "class_groups_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_memberships" ADD CONSTRAINT "group_memberships_class_group_id_fkey" FOREIGN KEY ("class_group_id") REFERENCES "class_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_memberships" ADD CONSTRAINT "group_memberships_enrollment_id_fkey" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_memberships" ADD CONSTRAINT "group_memberships_assigned_by_fkey" FOREIGN KEY ("assigned_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD CONSTRAINT "subjects_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "academic_periods" ADD CONSTRAINT "academic_periods_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_sessions" ADD CONSTRAINT "user_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
