import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1785537039854 implements MigrationInterface {
    name = 'InitialMigration1785537039854'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "user_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "refresh_token_hash" text NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked_at" TIMESTAMP WITH TIME ZONE, "remember_me" boolean NOT NULL DEFAULT false, "user_agent" character varying(500), "ip_address" inet, "last_used_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e93e031a5fed190d4789b6bfd83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."period_status" AS ENUM('DRAFT', 'ACTIVE', 'CLOSED')`);
        await queryRunner.query(`CREATE TABLE "academic_periods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "status" "public"."period_status" NOT NULL DEFAULT 'DRAFT', "created_by" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_c2d04cba0473190a799da160271" UNIQUE ("name"), CONSTRAINT "PK_911f414fba24e3855a5ba1f51ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subjects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(40) NOT NULL, "name" character varying(160) NOT NULL, "description" text, "active" boolean NOT NULL DEFAULT true, "created_by" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_542cbba74dde3c82ab49c573109" UNIQUE ("code"), CONSTRAINT "PK_1a023685ac2b051b4e557b0b280" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "students" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "full_name" character varying(180), "student_code" character varying(60) NOT NULL, "first_name" character varying(100) NOT NULL, "last_name" character varying(120) NOT NULL, "identity_number" character varying(40), "email" character varying(254), "phone" character varying(40), "photo_url" text, "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_94ea28a151d5f49f6bd4833466c" UNIQUE ("student_code"), CONSTRAINT "PK_7d7f07271ad4ce999880713f05e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."enrollment_status" AS ENUM('ACTIVE', 'WITHDRAWN', 'PASSED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "enrollments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "course_id" uuid NOT NULL, "student_id" uuid NOT NULL, "status" "public"."enrollment_status" NOT NULL DEFAULT 'ACTIVE', "enrolled_at" TIMESTAMP WITH TIME ZONE NOT NULL, "withdrawn_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7c0f752f9fb68bf6ed7367ab00f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "group_memberships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "class_group_id" uuid NOT NULL, "enrollment_id" uuid NOT NULL, "assigned_at" TIMESTAMP WITH TIME ZONE NOT NULL, "removed_at" TIMESTAMP WITH TIME ZONE, "assigned_by" uuid NOT NULL, "removal_reason" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4a04ebe9f25ad41f45b2c0ca4b5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."group_type" AS ENUM('LAB', 'PRACTICE', 'PROJECT', 'CUSTOM')`);
        await queryRunner.query(`CREATE TABLE "class_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "course_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "code" character varying(40) NOT NULL, "type" "public"."group_type" NOT NULL, "schedule" jsonb NOT NULL DEFAULT '[]', "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6c171cc3a186782e6c2cff1446b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."session_status" AS ENUM('PLANNED', 'OPEN', 'CLOSED', 'CANCELED')`);
        await queryRunner.query(`CREATE TABLE "class_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lesson_id" uuid NOT NULL, "course_id" uuid NOT NULL, "class_group_id" uuid, "session_date" date NOT NULL, "starts_at" TIMESTAMP WITH TIME ZONE NOT NULL, "ends_at" TIMESTAMP WITH TIME ZONE, "opened_at" TIMESTAMP WITH TIME ZONE, "closed_at" TIMESTAMP WITH TIME ZONE, "status" "public"."session_status" NOT NULL DEFAULT 'PLANNED', "topic_taught" text, "notes" text, "partial_override" smallint, "created_by" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_dc034da48c6e0cf95c51f606c4e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."lesson_type" AS ENUM('LECTURE', 'LAB', 'PRACTICE', 'EXAM', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "lessons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "course_id" uuid NOT NULL, "title" character varying(180) NOT NULL, "type" "public"."lesson_type" NOT NULL, "planned_topic" text, "sequence_number" integer, "created_by" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9b9a8d455cac672d262d7275730" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."course_status" AS ENUM('DRAFT', 'ACTIVE', 'CLOSED', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "courses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subject_id" uuid NOT NULL, "academic_period_id" uuid NOT NULL, "teacher_id" uuid NOT NULL, "parallel" character varying(30) NOT NULL, "modality" character varying(40), "schedule" jsonb NOT NULL DEFAULT '[]', "late_tolerance_minutes" integer NOT NULL DEFAULT '10', "status" "public"."course_status" NOT NULL DEFAULT 'DRAFT', "partial_1_ends_at" date, "partial_2_ends_at" date, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3f70a487cc718ad8eda4e6d58c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_role" AS ENUM('ADMIN', 'TEACHER', 'ASSISTANT')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "full_name" character varying(160) NOT NULL, "email" character varying(254) NOT NULL, "password_hash" text NOT NULL, "role" "public"."user_role" NOT NULL DEFAULT 'TEACHER', "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sync_status" AS ENUM('RECEIVED', 'APPLIED', 'CONFLICT', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "sync_operations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "client_operation_id" uuid NOT NULL, "user_id" uuid NOT NULL, "device_id" character varying(160) NOT NULL, "operation_type" character varying(100) NOT NULL, "payload_hash" character(64) NOT NULL, "status" "public"."sync_status" NOT NULL DEFAULT 'RECEIVED', "result_entity_type" character varying(100), "result_entity_id" uuid, "error_code" character varying(100), "received_at" TIMESTAMP WITH TIME ZONE NOT NULL, "processed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_10c716025524437a9eb3eaf855a" UNIQUE ("client_operation_id"), CONSTRAINT "PK_2d303195599690ecfcd3343de8a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."activity_type" AS ENUM('PRACTICE', 'LAB', 'HOMEWORK', 'PARTICIPATION', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."activity_grading_mode" AS ENUM('SCORE_0_100', 'SIGNATURES')`);
        await queryRunner.query(`CREATE TYPE "public"."activity_status" AS ENUM('DRAFT', 'OPEN', 'CLOSED')`);
        await queryRunner.query(`CREATE TABLE "activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "course_id" uuid NOT NULL, "lesson_id" uuid, "class_session_id" uuid, "title" character varying(180) NOT NULL, "type" "public"."activity_type" NOT NULL, "grading_mode" "public"."activity_grading_mode" NOT NULL DEFAULT 'SIGNATURES', "activity_date" date, "max_signatures" integer NOT NULL DEFAULT '1', "signature_value" numeric(8,2) NOT NULL DEFAULT '1', "status" "public"."activity_status" NOT NULL DEFAULT 'DRAFT', "notes" text, "created_by" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7f4004429f731ffb9c88eb486a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "exception_request_id" uuid NOT NULL, "storage_key" text NOT NULL, "original_name" character varying(255) NOT NULL, "mime_type" character varying(120) NOT NULL, "size_bytes" bigint NOT NULL, "checksum_sha256" character(64), "uploaded_by" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5e1f050bcff31e3084a1d662412" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."exception_type" AS ENUM('ABSENCE_JUSTIFICATION', 'OTHER_GROUP_ATTENDANCE', 'RECOVERY', 'LATE_REGISTRATION', 'ATTENDANCE_CORRECTION', 'MANUAL_SIGNATURE', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."exception_status" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_INFORMATION', 'CANCELED')`);
        await queryRunner.query(`CREATE TABLE "exception_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "course_id" uuid NOT NULL, "enrollment_id" uuid NOT NULL, "class_session_id" uuid, "activity_id" uuid, "type" "public"."exception_type" NOT NULL, "status" "public"."exception_status" NOT NULL DEFAULT 'PENDING', "reason" text NOT NULL, "requested_by" uuid NOT NULL, "requested_at" TIMESTAMP WITH TIME ZONE NOT NULL, "resolved_by" uuid, "resolved_at" TIMESTAMP WITH TIME ZONE, "resolution_note" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e45203b17c21c5e3834e9662b54" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."record_source" AS ENUM('QR', 'MANUAL', 'IMPORT', 'OFFLINE_SYNC')`);
        await queryRunner.query(`CREATE TABLE "signature_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activity_id" uuid NOT NULL, "enrollment_id" uuid NOT NULL, "class_session_id" uuid, "class_group_id" uuid, "quantity" integer NOT NULL DEFAULT '1', "source" "public"."record_source" NOT NULL, "registered_by" uuid NOT NULL, "exception_request_id" uuid, "comment" text, "registered_at" TIMESTAMP WITH TIME ZONE NOT NULL, "canceled_at" TIMESTAMP WITH TIME ZONE, "canceled_by" uuid, "cancellation_reason" text, "client_operation_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7e26854e261891fe12a5ea83c91" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "score_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "activity_id" uuid NOT NULL, "enrollment_id" uuid NOT NULL, "class_session_id" uuid, "score" numeric(5,2) NOT NULL, "registered_by" uuid NOT NULL, "comment" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_988486d0dcfb824da227de72a3e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "qr_credentials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "enrollment_id" uuid NOT NULL, "token_hash" text NOT NULL, "version" integer NOT NULL DEFAULT '1', "expires_at" TIMESTAMP WITH TIME ZONE, "revoked_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e01a0981c04840dbeefe258f3e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" SERIAL NOT NULL, "user_id" uuid, "entity_type" character varying(100) NOT NULL, "entity_id" uuid NOT NULL, "action" character varying(100) NOT NULL, "previous_data" jsonb, "new_data" jsonb, "request_id" uuid, "device_id" character varying(160), "ip_address" inet, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_status" AS ENUM('PRESENT', 'LATE', 'ABSENT', 'JUSTIFIED', 'EARLY_LEAVE')`);
        await queryRunner.query(`
          DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'record_source') THEN
              CREATE TYPE "public"."record_source" AS ENUM('QR', 'MANUAL', 'IMPORT', 'OFFLINE_SYNC');
            END IF;
          END$$;
        `);
        await queryRunner.query(`CREATE TABLE "attendance_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "class_session_id" uuid NOT NULL, "enrollment_id" uuid NOT NULL, "original_status" "public"."attendance_status" NOT NULL, "effective_status" "public"."attendance_status" NOT NULL, "check_in_at" TIMESTAMP WITH TIME ZONE, "check_out_at" TIMESTAMP WITH TIME ZONE, "source" "public"."record_source" NOT NULL, "registered_by" uuid NOT NULL, "exception_request_id" uuid, "comment" text, "client_operation_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_946920332f5bc9efad3f3023b96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sheet_sync_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "course_id" uuid NOT NULL, "class_id" uuid, "reason" character varying(40) NOT NULL, "revision" integer NOT NULL DEFAULT '1', "status" character varying(40) NOT NULL DEFAULT 'PENDING', "attempts" integer NOT NULL DEFAULT '0', "last_error" text, "started_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a6a9d36185cb0526ae191eec142" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "google_integration_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "owner_user_id" uuid NOT NULL, "project_id" character varying(200) NOT NULL, "service_account_email" character varying(254) NOT NULL, "encrypted_private_key" text NOT NULL, "share_with_email" character varying(254), "status" character varying(40) NOT NULL DEFAULT 'ACTIVE', "last_validated_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f68e078e9dda66cd24d8e866c1c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "course_spreadsheets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "course_id" uuid NOT NULL, "google_integration_setting_id" uuid, "spreadsheet_id" character varying(120), "spreadsheet_url" text, "spreadsheet_name" character varying(300), "template_version" integer NOT NULL DEFAULT '1', "status" character varying(40) NOT NULL DEFAULT 'NOT_CONFIGURED', "last_synced_at" TIMESTAMP WITH TIME ZONE, "last_synced_class_id" uuid, "last_error" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_a0ead76f76ec79ca52aa5f2f832" UNIQUE ("course_id"), CONSTRAINT "UQ_f55a0361779e38d76707dffc09d" UNIQUE ("spreadsheet_id"), CONSTRAINT "PK_b1ab387a5fc01269a39e5442db0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "user_sessions" ADD CONSTRAINT "FK_e9658e959c490b0a634dfc54783" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "academic_periods" ADD CONSTRAINT "FK_ce7321356447fb7ff25796bf01b" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subjects" ADD CONSTRAINT "FK_c9006b576b282e18dba027d6a38" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_b79d0bf01779fdf9cfb6b092af3" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrollments" ADD CONSTRAINT "FK_307813fe255896d6ebf3e6cd55c" FOREIGN KEY ("student_id") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_memberships" ADD CONSTRAINT "FK_201a35ba15360d2be0f49f87968" FOREIGN KEY ("class_group_id") REFERENCES "class_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_memberships" ADD CONSTRAINT "FK_eaf10f573c6658ad490ef2be10a" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_memberships" ADD CONSTRAINT "FK_205d85b0fa4d4e1e6b0a7d6f187" FOREIGN KEY ("assigned_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_groups" ADD CONSTRAINT "FK_c049df9d565461e9fab4de361af" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_sessions" ADD CONSTRAINT "FK_05aba5b1dd690db8dd7c06919e9" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_sessions" ADD CONSTRAINT "FK_1397d1e5d657291c564326ef505" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_sessions" ADD CONSTRAINT "FK_355019a6577e38674ddfa5bd264" FOREIGN KEY ("class_group_id") REFERENCES "class_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_sessions" ADD CONSTRAINT "FK_1ecd9efd9287f6532bc2bb2f354" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_3c4e299cf8ed04093935e2e22fe" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_b96adc7c3e06624edae3e0a01ae" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_05f921ecf5310e1204a95d824a9" FOREIGN KEY ("subject_id") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_35dbc76f1896b96d63bc7a23329" FOREIGN KEY ("academic_period_id") REFERENCES "academic_periods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_fad76a730ee7f68d0a59652fb12" FOREIGN KEY ("teacher_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sync_operations" ADD CONSTRAINT "FK_fc210cc9a22c0feee5e88a27ae9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_5c2d04397bd5264e1f7a7ac2deb" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_8be9a128683642f952474cbc22c" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_4ea111d4bedad24f545d45c99f1" FOREIGN KEY ("class_session_id") REFERENCES "class_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activities" ADD CONSTRAINT "FK_eadf67c38263ba30b296d40f033" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_c2372cfa0329dfd4c86cc2cc294" FOREIGN KEY ("exception_request_id") REFERENCES "exception_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_e25812e3fd9b3f3edf11b2c5d58" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "FK_31e5a9f12a347c6d5f479ee18a7" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "FK_f1d43ae3dee5680d47fd90412a2" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "FK_e255e1307395d3b65c717023b8f" FOREIGN KEY ("class_session_id") REFERENCES "class_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "FK_917be94d76ac1a0aa1f37995e89" FOREIGN KEY ("activity_id") REFERENCES "activities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "FK_1287c7c37b03b712ddd4b37a28d" FOREIGN KEY ("requested_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exception_requests" ADD CONSTRAINT "FK_e7ed486410813c9cb952e095c43" FOREIGN KEY ("resolved_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "FK_8186ada3c3903b1629e83cbe919" FOREIGN KEY ("activity_id") REFERENCES "activities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "FK_e0689b96ec280bb421ac61ef16c" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "FK_df6155c0558ff1dec25dd159f3c" FOREIGN KEY ("class_session_id") REFERENCES "class_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "FK_ffd5b0acc25ed64ac8ccd0e8906" FOREIGN KEY ("class_group_id") REFERENCES "class_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "FK_e764583de484ea61eadd00bd611" FOREIGN KEY ("registered_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "FK_4540b5657a6ed221808922077fd" FOREIGN KEY ("exception_request_id") REFERENCES "exception_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "signature_records" ADD CONSTRAINT "FK_5ff9bdcc5783744c7825e86df3c" FOREIGN KEY ("canceled_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "score_records" ADD CONSTRAINT "FK_7ea7a0d0beda4c30334ab757234" FOREIGN KEY ("activity_id") REFERENCES "activities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "score_records" ADD CONSTRAINT "FK_2336887e0ee83d449497407c956" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "score_records" ADD CONSTRAINT "FK_7fd45ee5e78625b4597407db9b5" FOREIGN KEY ("class_session_id") REFERENCES "class_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "score_records" ADD CONSTRAINT "FK_97bd9b64dc56d89a652d22f5d33" FOREIGN KEY ("registered_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" ADD CONSTRAINT "FK_805dcea713b2ca37de557ec2ac9" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" ADD CONSTRAINT "FK_ef95cecc71ad1443d04f9be1c0f" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_8c6d588fe4bc0388eb669fcc5f8" FOREIGN KEY ("class_session_id") REFERENCES "class_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_ac1298d6bec15b271f734c4e5d6" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_ab6c85ec19c440d0bbe1ede0ae5" FOREIGN KEY ("registered_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_c2a103593762e0cb91dcdf0f3d2" FOREIGN KEY ("exception_request_id") REFERENCES "exception_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sheet_sync_jobs" ADD CONSTRAINT "FK_bc18127b3642846c1fc649f4b2f" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "google_integration_settings" ADD CONSTRAINT "FK_400647045b5bf8cdfa7ada5c413" FOREIGN KEY ("owner_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_spreadsheets" ADD CONSTRAINT "FK_a0ead76f76ec79ca52aa5f2f832" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "course_spreadsheets" ADD CONSTRAINT "FK_284427e3fa9d3ead56698f5623d" FOREIGN KEY ("google_integration_setting_id") REFERENCES "google_integration_settings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "course_spreadsheets" DROP CONSTRAINT "FK_284427e3fa9d3ead56698f5623d"`);
        await queryRunner.query(`ALTER TABLE "course_spreadsheets" DROP CONSTRAINT "FK_a0ead76f76ec79ca52aa5f2f832"`);
        await queryRunner.query(`ALTER TABLE "google_integration_settings" DROP CONSTRAINT "FK_400647045b5bf8cdfa7ada5c413"`);
        await queryRunner.query(`ALTER TABLE "sheet_sync_jobs" DROP CONSTRAINT "FK_bc18127b3642846c1fc649f4b2f"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_c2a103593762e0cb91dcdf0f3d2"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_ab6c85ec19c440d0bbe1ede0ae5"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_ac1298d6bec15b271f734c4e5d6"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_8c6d588fe4bc0388eb669fcc5f8"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" DROP CONSTRAINT "FK_ef95cecc71ad1443d04f9be1c0f"`);
        await queryRunner.query(`ALTER TABLE "qr_credentials" DROP CONSTRAINT "FK_805dcea713b2ca37de557ec2ac9"`);
        await queryRunner.query(`ALTER TABLE "score_records" DROP CONSTRAINT "FK_97bd9b64dc56d89a652d22f5d33"`);
        await queryRunner.query(`ALTER TABLE "score_records" DROP CONSTRAINT "FK_7fd45ee5e78625b4597407db9b5"`);
        await queryRunner.query(`ALTER TABLE "score_records" DROP CONSTRAINT "FK_2336887e0ee83d449497407c956"`);
        await queryRunner.query(`ALTER TABLE "score_records" DROP CONSTRAINT "FK_7ea7a0d0beda4c30334ab757234"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "FK_5ff9bdcc5783744c7825e86df3c"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "FK_4540b5657a6ed221808922077fd"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "FK_e764583de484ea61eadd00bd611"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "FK_ffd5b0acc25ed64ac8ccd0e8906"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "FK_df6155c0558ff1dec25dd159f3c"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "FK_e0689b96ec280bb421ac61ef16c"`);
        await queryRunner.query(`ALTER TABLE "signature_records" DROP CONSTRAINT "FK_8186ada3c3903b1629e83cbe919"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "FK_e7ed486410813c9cb952e095c43"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "FK_1287c7c37b03b712ddd4b37a28d"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "FK_917be94d76ac1a0aa1f37995e89"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "FK_e255e1307395d3b65c717023b8f"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "FK_f1d43ae3dee5680d47fd90412a2"`);
        await queryRunner.query(`ALTER TABLE "exception_requests" DROP CONSTRAINT "FK_31e5a9f12a347c6d5f479ee18a7"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_e25812e3fd9b3f3edf11b2c5d58"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_c2372cfa0329dfd4c86cc2cc294"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_eadf67c38263ba30b296d40f033"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_4ea111d4bedad24f545d45c99f1"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_8be9a128683642f952474cbc22c"`);
        await queryRunner.query(`ALTER TABLE "activities" DROP CONSTRAINT "FK_5c2d04397bd5264e1f7a7ac2deb"`);
        await queryRunner.query(`ALTER TABLE "sync_operations" DROP CONSTRAINT "FK_fc210cc9a22c0feee5e88a27ae9"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_fad76a730ee7f68d0a59652fb12"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_35dbc76f1896b96d63bc7a23329"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_05f921ecf5310e1204a95d824a9"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "FK_b96adc7c3e06624edae3e0a01ae"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "FK_3c4e299cf8ed04093935e2e22fe"`);
        await queryRunner.query(`ALTER TABLE "class_sessions" DROP CONSTRAINT "FK_1ecd9efd9287f6532bc2bb2f354"`);
        await queryRunner.query(`ALTER TABLE "class_sessions" DROP CONSTRAINT "FK_355019a6577e38674ddfa5bd264"`);
        await queryRunner.query(`ALTER TABLE "class_sessions" DROP CONSTRAINT "FK_1397d1e5d657291c564326ef505"`);
        await queryRunner.query(`ALTER TABLE "class_sessions" DROP CONSTRAINT "FK_05aba5b1dd690db8dd7c06919e9"`);
        await queryRunner.query(`ALTER TABLE "class_groups" DROP CONSTRAINT "FK_c049df9d565461e9fab4de361af"`);
        await queryRunner.query(`ALTER TABLE "group_memberships" DROP CONSTRAINT "FK_205d85b0fa4d4e1e6b0a7d6f187"`);
        await queryRunner.query(`ALTER TABLE "group_memberships" DROP CONSTRAINT "FK_eaf10f573c6658ad490ef2be10a"`);
        await queryRunner.query(`ALTER TABLE "group_memberships" DROP CONSTRAINT "FK_201a35ba15360d2be0f49f87968"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_307813fe255896d6ebf3e6cd55c"`);
        await queryRunner.query(`ALTER TABLE "enrollments" DROP CONSTRAINT "FK_b79d0bf01779fdf9cfb6b092af3"`);
        await queryRunner.query(`ALTER TABLE "subjects" DROP CONSTRAINT "FK_c9006b576b282e18dba027d6a38"`);
        await queryRunner.query(`ALTER TABLE "academic_periods" DROP CONSTRAINT "FK_ce7321356447fb7ff25796bf01b"`);
        await queryRunner.query(`ALTER TABLE "user_sessions" DROP CONSTRAINT "FK_e9658e959c490b0a634dfc54783"`);
        await queryRunner.query(`DROP TABLE "course_spreadsheets"`);
        await queryRunner.query(`DROP TABLE "google_integration_settings"`);
        await queryRunner.query(`DROP TABLE "sheet_sync_jobs"`);
        await queryRunner.query(`DROP TABLE "attendance_records"`);
        await queryRunner.query(`DROP TYPE "public"."record_source"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_status"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "qr_credentials"`);
        await queryRunner.query(`DROP TABLE "score_records"`);
        await queryRunner.query(`DROP TABLE "signature_records"`);
        await queryRunner.query(`DROP TABLE "exception_requests"`);
        await queryRunner.query(`DROP TYPE "public"."exception_status"`);
        await queryRunner.query(`DROP TYPE "public"."exception_type"`);
        await queryRunner.query(`DROP TABLE "attachments"`);
        await queryRunner.query(`DROP TABLE "activities"`);
        await queryRunner.query(`DROP TYPE "public"."activity_status"`);
        await queryRunner.query(`DROP TYPE "public"."activity_grading_mode"`);
        await queryRunner.query(`DROP TYPE "public"."activity_type"`);
        await queryRunner.query(`DROP TABLE "sync_operations"`);
        await queryRunner.query(`DROP TYPE "public"."sync_status"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."user_role"`);
        await queryRunner.query(`DROP TABLE "courses"`);
        await queryRunner.query(`DROP TYPE "public"."course_status"`);
        await queryRunner.query(`DROP TABLE "lessons"`);
        await queryRunner.query(`DROP TYPE "public"."lesson_type"`);
        await queryRunner.query(`DROP TABLE "class_sessions"`);
        await queryRunner.query(`DROP TYPE "public"."session_status"`);
        await queryRunner.query(`DROP TABLE "class_groups"`);
        await queryRunner.query(`DROP TYPE "public"."group_type"`);
        await queryRunner.query(`DROP TABLE "group_memberships"`);
        await queryRunner.query(`DROP TABLE "enrollments"`);
        await queryRunner.query(`DROP TYPE "public"."enrollment_status"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP TABLE "subjects"`);
        await queryRunner.query(`DROP TABLE "academic_periods"`);
        await queryRunner.query(`DROP TYPE "public"."period_status"`);
        await queryRunner.query(`DROP TABLE "user_sessions"`);
    }

}
